### ISSUE TITLE
Pie chart order not by value

### ISSUE THREAD

**Issue by andresgutgon** [plouc/nivo#68]
### What?
Hi, I would like to order pie segments not by value. I would like to order for example in my case by `label`

![image](https://user-images.githubusercontent.com/49499/31431881-38ee7100-ae75-11e7-9cc9-feb362504a6e.png)

In my case I would like to order:
1. `label 1`
2. `label 2`
3. `label 3`

But pie looks like is always by `value`.  I don't see any way to configure `order` https://github.com/plouc/nivo/blob/master/src/components/charts/pie/Pie.js#L108

Is there something I can do? I wouldn't mine do a pull request to change it but first I would like if there is already a way to do it

**Comment by plouc** [comment]
Hi @andresgutgon, for now it's not possible, but it should be, the Pie layout from d3 allow this, it's just a matter of exposing it through the nivo API, for now I'm pretty busy, but I'll try something when I have more free time.

**Comment by andresgutgon** [comment]
Great! I will try to do a PR

**Comment by plouc** [comment]
You can have a look at the stream component then, which support other sort functions.

**Comment by plouc** [comment]
Fixed by https://github.com/plouc/nivo/pull/79, now arcs won't be ordered by value by default, the default dataset order will be used, to enable sorting by value, we now must explicitly set `sortByValue` to `true`.

**Comment by plouc** [comment]
@andresgutgon available in `nivo@0.30.0`

**Comment by andresgutgon** [comment]
Thanks!

**Comment by usamedin** [comment]
This is still an issue, randomly changing the order of the items even i am always sending the data in single order
